### ISSUE TITLE
[Request] Itemizer integration and item drops

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Brawlator#1]
Add itemizer item and pool support.
the example config below will always drop the item "Bronze Dagger" and  the minecraft item "bone" as well as roll both item pools and drop both items (if any) that are returned.

```
monsters=[
    {
        damage=1.0
        hp=50.0
        knockbackResistance=1
        name="Tank archer"
        speed=1.0
        type=skeleton
        drops: [
            item: {name: "minecraft:bone"},
            item: {ref: "Bronze Dagger"}, //will always drop itemizer item "Bronze Dagger"
            pool: {ref: 1}, //will always look into Itemizer Pool and return value
            pool: {ref: 21} //will always look into Itemizer Pool and return value
        ]
    }
]
```

**Comment by zessirb** [comment]
Good news, we have an implemented drop pool system! (still in [1.2.0](https://github.com/OnapleRPG/Brawlator/releases/download/1.2.0/Brawlator-1.2.0.jar))  
It's among the default generated config in the "loot.conf" config file. Here is how it works:
- Define loots following our standard, where each loot corresponds to 1 possible items (or nothing) with a weight system  
```
{
    probability : 0.75
    name : "table1"
    loot : [
      {
        weight : 0.5
        ref : "training_stick"
      },
      {
        weight : 0.5
        poolId : 1
      }
    ]
  }
```
The loot above have a 75% probability of trying to give you a loot.  
If it is triggered, you then have a 50% chance of droping an itemizer item with id "training_stick" and a 50% chance to give you an item from Itemizer pool with id 1. (it's cumulative, so adding more items is useless since we already reached 100% with all items)  
- Within the monster config file, add a field "pools" to your monster. It must be an array with the id(s) of your pool (table1 for this case).  
If you specify multiple pools, then it will query every pools separately.
