### ISSUE TITLE
[REQUEST] Debug mode logging toggle

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Brawlator#5]
Currently in Brawlator there is a constant stream of very useful information when developing; however it floods the logs and makes troubleshooting other plugins more difficult.

Can an option be added that enables/disables this logging into the global config?

**Comment by zessirb** [comment]
That was a mistake on our side, we are definitely not supposed to be that verbose.  
The last version ([1.2.0](https://github.com/OnapleRPG/Brawlator/releases/download/1.2.0/Brawlator-1.2.0.jar)) have a logging system more alike our other plugins. It is a bit more verbose than the other because there is more events happening in the beginning, but you won't be annoyed by that lovecraftian horror of a console anymore :)  
If you believe it is still too verbose, please contact us, we can adjust that.
